### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by nick2474** [lbaldi/it#11]
Why is showing the following error: ? Is missing some dependencies?

Traceback (most recent call last):
  File "/home/erp_user/openerp/demo_v8/server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/erp_user/openerp/demo_v8/server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/erp_user/openerp/demo_v8/server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/erp_user/openerp/demo_v8/server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/erp_user/openerp/demo_v8/server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/erp_user/openerp/demo_v8/server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/erp_user/openerp/demo_v8/server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/erp_user/openerp/demo_v8/server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/erp_user/openerp/demo_v8/server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/erp_user/openerp/demo_v8/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/erp_user/openerp/demo_v8/server/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/erp_user/openerp/demo_v8/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/erp_user/openerp/demo_v8/server/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/erp_user/openerp/demo_v8/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/erp_user/openerp/demo_v8/server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/erp_user/openerp/demo_v8/server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/erp_user/openerp/demo_v8/server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/erp_user/openerp/demo_v8/server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/erp_user/openerp/demo_v8/server/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/erp_user/openerp/demo_v8/server/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/erp_user/openerp/demo_v8/server/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/erp_user/openerp/demo_v8/server/openerp/tools/convert.py", line 540, in _tag_menuitem
    self._test_xml_id(rec_id)
  File "/home/erp_user/openerp/demo_v8/server/openerp/tools/convert.py", line 289, in _test_xml_id
    assert modcnt == 1, """The ID "%s" refers to an uninstalled module""" % (xml_id,)
ParseError: "The ID "it.menu_main_itm" refers to an uninstalled module" while parsing /home/erp_user/openerp/demo_v8/server/addons/it_management/views/it_menu_view.xml:25, near
<menuitem name="Infrastructure" id="it.menu_main_itm" sequence="42"/>

**Comment by lbaldi** [comment]
Your addons module name should be "it" not "it_management".

**Comment by nick2474** [comment]
Ok, its work fine, after change the directory to IT.

What's about V9? I m getting error:

Odoo Server Error
Traceback (most recent call last):
  File "/home/erp_user/openerp/idactivos_v9/server/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/erp_user/openerp/idactivos_v9/server/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/home/erp_user/openerp/idactivos_v9/server/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/erp_user/openerp/idactivos_v9/server/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
Element '<xpath expr="//div[@name='buttons']">' cannot be located in parent view

Error context:
View `it.partner.view`
[view_id: 840, xml_id: n/a, model: res.partner, parent_id: 123]
None" while parsing /home/erp_user/openerp/idactivos_v9/server/addons/it/views/partner_view.xml:81, near
<record id="it_partner_view2" model="ir.ui.view">
            <field name="name">it.partner.view</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_partner_form"/>
            <field name="arch" type="xml">
                <data>
                    <xpath expr="//div[@name='buttons']" position="inside">
                        <button name="%(act_partner_2_equipment)d" class="oe_inline oe_stat_button" icon="fa-th-large" type="action" groups="it.group_it_user" attrs="{'invisible':[('manage_it','=', False )]}">
                                    <field name="equipment_count" widget="statinfo"/>
                        </button>
                        <button name="%(act_partner_2_access)d" class="oe_inline oe_stat_button" icon="fa-key" type="action" groups="it.group_it_user" attrs="{'invisible':[('manage_it','=', False )]}">
                                    <field name="access_count" widget="statinfo"/>
                        </button>
                        <button name="%(act_partner_2_backup)d" class="oe_inline oe_stat_button" icon="fa-floppy-o" type="action" groups="it.group_it_user" attrs="{'invisible':[('manage_it','=', False )]}">
                                    <field name="backup_count" widget="statinfo"/>
                        </button>
                    </xpath>
                </data>
            </field>
        </record>

**Comment by lbaldi** [comment]
Seem to be problems with partner's view in v9. Module's version is v8.
